# =============================================================================
# ⚡ TILT SDK - VITE FRONTEND GENERATOR
load("../../../../spec.master", "OUTPUT")
load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')
# =============================================================================
# Path: .tilt/providers/vite/frontend.star
# Purpose: Vite config generator for Frontend services
# =============================================================================

load('../../../../../.tilt/TILT_SERVICE_DEFAULTS.star', 'BASE_PORT_FRONTEND', 'BASE_PORT_BACKEND')
load('./templates.star', 'TEMPLATE_VITE_FRONTEND', 'TEMPLATE_VITE_FRONTEND_BUILD')
load('./helpers.star', 
    'build_header', 
    'generate_frontend_internal_aliases', 
    'generate_frontend_optimize_deps', 
    'generate_proxy_block'
)

# Constants for output paths
VITE_FRONTEND_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_frontend']
VITE_FRONTEND_BUILD_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_build']

def _normalize_vite_base_path(base_path):
    """Vite subpath deploys are more reliable with a trailing slash."""
    if not base_path:
        return '/'
    if not base_path.startswith('/'):
        base_path = '/' + base_path
    if base_path != '/' and not base_path.endswith('/'):
        base_path = base_path + '/'
    return base_path

def generate_frontend(manifest, backend_manifest=None, write_fn=None):
    """
    Generate vite.config.ts for FRONTEND services.
    
    Features:
    - Auto-proxy to backend based on backend manifest port
    - HMR configuration with correct ports
    - Base path configuration
    - TypeScript path aliases
    - 🔥 Auto-generated internal dependency aliases from package.json
    - 🔥 optimizeDeps.include for faster dev startup
    """
    if manifest.get('appType') != 'frontend':
        fail("Vite.frontend() requires a frontend manifest, got: " + manifest.get('appType', 'unknown'))
    
    service_path = manifest.get('_servicePath', '')
    domain = manifest.get('domain', 'app')
    port = manifest.get('port', BASE_PORT_FRONTEND)
    hmr_port = manifest.get('hmrPort', port + 1000)
    base_path = manifest.get('basePath', '/' + domain + 's')
    vite_base_path = _normalize_vite_base_path(base_path)
    app_name = manifest.get('appName', 'unknown')
    
    backend_port = BASE_PORT_BACKEND
    if backend_manifest:
        backend_port = backend_manifest.get('port', BASE_PORT_BACKEND)
    
    api_base_path = manifest.get('apiBasePath', '/api')
    proxy_routes = manifest.get('proxyRoutes', [])
    
    proxy_config = generate_proxy_block(api_base_path, backend_port, proxy_routes, domain)
    header = build_header('Vite.frontend()', app_name)
    # Config is written under autogenerated/, so aliases need one extra ".." level.
    internal_aliases = generate_frontend_internal_aliases(service_path, manifest, 1)
    optimize_deps_include = generate_frontend_optimize_deps(manifest)
    
    config = TEMPLATE_VITE_FRONTEND.format(
        header=header,
        base_path=vite_base_path,
        port=port,
        hmr_port=hmr_port,
        proxy_config=proxy_config,
        internal_aliases=internal_aliases,
        optimize_deps_include=optimize_deps_include,
    )

    build_cfg_header = build_header('Vite.frontend()', app_name, 'Build-only Vite config')
    build_config = TEMPLATE_VITE_FRONTEND_BUILD.format(
        header=build_cfg_header,
        base_path=vite_base_path,
        optimize_deps_include=optimize_deps_include,
    )
    
    if write_fn:
        write_fn(service_path + VITE_FRONTEND_CONFIG_PATH, config)
        write_fn(service_path + VITE_FRONTEND_BUILD_CONFIG_PATH, build_config)
    
    return config
