# =============================================================================
# 🐳 TILT SDK - DOCKER COMPOSE GENERATORS (modular)
# =============================================================================
# Path: .tilt/topologies/platform/docker/compose.star
# Purpose: docker-compose generation helpers extracted from .tilt/providers/docker.star
# =============================================================================

load("./compose_helpers.star", "with_runtime_image_tag", "compose_build_config")
load("../networking/traefik.star", "get_frontend_traefik_labels", "get_backend_traefik_labels")
load("../networking/api_path_constants.star", "get_api_path_for_domain")
load("../secrets/infisical.star", "get_infisical_environment_vars")
load("../auth/auth.star", "AuthConfig")
load("../../../../spec.master", "OUTPUT")
load("../constants.star", "PlatformDockerConstants")
load("../../../../../.tilt/TILT_SERVICE_DEFAULTS.star", "BASE_PORT_FRONTEND", "BASE_PORT_BACKEND", "HEALTH_CHECK_PATH")

def _compute_env_file_rel_path(service_path, full_service_path, env_filename):
    """
    Compute the relative path from compose file location to env file.
    
    The compose file is at: service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER/docker-compose.app.autogenerated.yml'
    The env file is at: full_service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + env_filename
    
    Args:
        service_path: The domain/service group path (e.g., 'services/product/identity' or 'services/platform')
        full_service_path: The actual service path (e.g., 'services/product/identity/identity-management-backend' or 'shared-product-engineering/introvertic/infra')
        env_filename: The env file name (e.g., '.env.frontend.autogenerated' or '.env.backend.autogenerated')
    
    Returns:
        Relative path from compose file to env file
    """
    # Count how many levels deep the compose file is
    # service_path like 'services/product/identity' has 3 parts
    # compose file is at service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/', so we need len(parts) + 1 levels of ../
    service_path_parts = service_path.split('/')
    num_dotdots = len(service_path_parts) + 1  # +1 for the autogenerated directory
    
    # Build the dotdot prefix
    dotdot_prefix = '/'.join(['..'] * num_dotdots)
    
    # The env file is at full_service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + env_filename
    return dotdot_prefix + '/' + full_service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + env_filename

# =============================================================================
# 🚦 FRONTEND / BACKEND ENTRIES
# =============================================================================

def generate_frontend_compose(service_path, service_name, res, manifest=None):
    """Generate frontend docker-compose entry with Traefik routing."""
    res_name = res['name']
    image_name = with_runtime_image_tag(service_name + '_' + res_name)
    domain = manifest.get('domain', service_name) if manifest else service_name
    
    target_path = res.get('target_path', manifest.get('target_path', '/usr/share/nginx/html'))
    use_nginx = 'nginx' in target_path or target_path == '/usr/share/nginx/html'
    port = 80 if use_nginx else BASE_PORT_FRONTEND
    
    # Base path for routing on TDK Landscape.localhost
    base_path = '/' + manifest.get('basePath', domain + 's').lstrip('/')
    
    traefik_cfg = manifest.get('traefik', {}) if manifest else {}
    traefik_host = traefik_cfg.get('host')
    # Use custom dockerfile from manifest if specified, otherwise use autogenerated default
    dockerfile_path = res.get('dockerfile', OUTPUT.AUTOGENERATED_FOLDER + '/Dockerfile.app.autogenerated')
    # Handle flat service structure (e.g., services/product/mdblaster-docs) vs nested (services/product/domain/service)
    # Detect flat structure: services/product/{service} (3 path parts after root) 
    # vs nested: services/product/{domain}/{service} (4+ path parts)
    full_service_path = res.get('_service_path', service_path + '/' + res_name)
    path_parts = full_service_path.split('/')
    # If path is like services/product/xxx (3 parts), it's flat - use path directly
    # If path is like services/product/domain/xxx (4 parts), it's nested - use standard construction
    if len(path_parts) <= 3:
        # Flat structure: service_path already includes res_name
        build_config = compose_build_config(full_service_path, '', dockerfile_path, 'production')
    else:
        # Nested structure: use service_path and res_name separately
        build_config = compose_build_config(service_path, res_name, dockerfile_path, 'production')
    
    # Calculate correct relative path to env_file from compose file location
    # The compose file is at: service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER/docker-compose.app.autogenerated.yml'
    # The env file is at: full_service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER/.env.frontend.autogenerated'
    env_file_rel_path = _compute_env_file_rel_path(service_path, full_service_path, '.env.frontend.autogenerated')
    
    traefik_labels = get_frontend_traefik_labels(
        res_name,
        domain,
        base_path,
        port,
        traefik_host=traefik_host,
        manifest=manifest,
    )
    
    return """  {res_name}:
    image: {image_name}
{build_config}
    <<: *frontend-memory-limit
    env_file:
      - {env_file_rel_path}
    environment:
        - VITE_APP_ENV=development
    labels:
{traefik_labels}
    networks:
        - {network_traefik_public}
        - {network_backend}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:{port}"]
      interval: 10s
      timeout: 5s
      retries: 3
      # STORY 4 FIX: 30s grace period to prevent 504 errors on startup
      start_period: 30s
""".format(
        res_name=res_name, 
        image_name=image_name,
        build_config=build_config,
        env_file_rel_path=env_file_rel_path,
        traefik_labels=traefik_labels,
        port=port,
        network_traefik_public=PlatformDockerConstants.NETWORK_TRAEFIK_PUBLIC,
        network_backend=PlatformDockerConstants.NETWORK_BACKEND,
    )


def _generate_single_backend_entry(service_path, service_name, res, manifest, instance_id=None):
    """
    Generate a single backend docker-compose entry.
    """
    res_name = res['name']
    domain = manifest.get('domain', service_name) if manifest else service_name
    
    # Get full service path from resource (for cross-root service support)
    full_service_path = res.get('_service_path', service_path + '/' + res_name)
    
    # Calculate correct relative path to env_file from compose file location
    env_file_rel_path = _compute_env_file_rel_path(service_path, full_service_path, '.env.backend.autogenerated')
    
    internal_port = BASE_PORT_FRONTEND
    dev_port = manifest.get('port', BASE_PORT_BACKEND) if manifest else BASE_PORT_BACKEND
    db_name = manifest.get('databaseName', 'TDK_' + domain) if manifest else 'TDK_' + domain
    
    # Compute database URLs using centralized constants
    db_url_for_tilt = PlatformDockerConstants.get_database_url_for_env(db_name)
    db_url_with_fallback = PlatformDockerConstants.get_compose_env_database_url(db_name)
    
    health_path = manifest.get('healthCheckPath', HEALTH_CHECK_PATH) if manifest else HEALTH_CHECK_PATH
    
    traefik_cfg = manifest.get('traefik', {}) if manifest else {}
    traefik_host = traefik_cfg.get('host', domain + '.backend.beauty.local')
    # ALPHA: Use proper API v1 path with -management suffix via api_path_constants
    # Old default: '/api/' + domain
    # New default: get_api_path_for_domain → /api/v1/{domain}-management
    traefik_path = traefik_cfg.get('pathPrefix', get_api_path_for_domain(domain, manifest))
    
    nats_cfg = manifest.get('nats', {}) if manifest else {}
    nats_queue = nats_cfg.get('queueGroup', domain + '_backend_svc')
    nats_url = PlatformDockerConstants.NATS_URL
    
    # Auth configuration - use centralized auth utilities
    # Extract auth config from manifest to decouple auth.star from manifest structure
    # Auto-detect identity-service mode if 'identity' is in internalDependencies
    internal_deps = manifest.get('internalDependencies', []) if manifest else []
    has_identity_dep = 'identity' in internal_deps
    
    # If manifest has authMode, use it; otherwise auto-detect based on identity dependency
    manifest_auth_mode = manifest.get('authMode') if manifest else None
    if manifest_auth_mode:
        auth_mode = manifest_auth_mode
    elif has_identity_dep:
        auth_mode = 'identity-service'
    else:
        auth_mode = None
    
    auth_config = {
        'authMode': auth_mode,
        'jwtSecret': manifest.get('jwtSecret') if manifest else None,
        'identityServiceUrl': manifest.get('envVars', {}).get('IDENTITY_SERVICE_URL') if manifest else None,
    }
    
    # If we auto-detected identity-service mode but no URL is set, use default
    if auth_mode == 'identity-service' and not auth_config['identityServiceUrl']:
        auth_config['identityServiceUrl'] = AuthConfig.get_identity_service_url(None)
    
    auth_env = AuthConfig.generate_docker_compose_auth_env(auth_config)
    
    # Use autogenerated/Dockerfile.app.autogenerated by default for build config (primary only)
    build_config = compose_build_config(service_path, res_name)
    
    # REMOVED: External port exposure - all services accessed via Traefik only
    # Services are available at TDK Landscape.localhost/api/v1/{service}
    # Internal port 3000 is accessible within Docker network for service-to-service communication
    ports_section = ""  # No external ports - Traefik-only access
    
    # Determine service name based on instance
    if instance_id:
        # Replica instance: add instance suffix
        service_entry_name = res_name + '-' + str(instance_id)
        instance_label = str(instance_id)
        # Replicas should reuse the already-built image; avoid per-replica builds
        build_config = ""
    else:
        # Primary instance
        service_entry_name = res_name
        instance_label = '0'
    
    # All instances share the same Traefik service for load balancing
    traefik_service_name = res_name  # LB service name (shared)
    
    traefik_labels = get_backend_traefik_labels(
        service_entry_name=service_entry_name, 
        traefik_host=traefik_host, 
        traefik_path=traefik_path, 
        traefik_service_name=traefik_service_name, 
        internal_port=internal_port, 
        health_path=health_path,
        manifest=manifest,
    )
    infisical_env = get_infisical_environment_vars(as_array=True)
    
    # Build auth environment variables section using centralized auth utilities
    
    return """
  {service_entry_name}:
    image: {image_name}
    restart: unless-stopped
{build_config}
{ports_section}
    env_file:
      - {env_file_rel_path}
    environment:
{infisical_env}
      - SERVICE_NAME={domain}
      - PORT={internal_port}
      - INSTANCE_ID={instance_label}
      - NATS_QUEUE_GROUP={nats_queue}
      - TILT_DATABASE_URL={db_url_for_tilt}
      - TILT_NATS_URL={nats_url}
      - NODE_ENV=development
      - DATABASE_URL={db_url_for_tilt}
{auth_env}
    labels:
{traefik_labels}
    networks:
      - {network_traefik_public}
      - {network_backend}
      - {network_database}
      - {network_infisical}
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "5", "http://localhost:{internal_port}{health_path}"]
      interval: 10s
      timeout: 5s
      retries: 6
      # STORY 4 FIX: 30s grace period to prevent 504 errors during startup
      # Services get 30s to initialize before health checks begin
      start_period: 30s
    # Note: depends_on removed - Tilt manages service startup order
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
""".format(
        service_entry_name=service_entry_name,
        res_name=res_name, 
        service_name=service_name, 
        image_name=with_runtime_image_tag(service_name + '_' + res_name),
        build_config=build_config,
        ports_section=ports_section,
        env_file_rel_path=env_file_rel_path,
        domain=domain,
        internal_port=internal_port,
        dev_port=dev_port,
        db_name=db_name,
        db_url_for_tilt=db_url_for_tilt,
        db_url_with_fallback=db_url_with_fallback,
        instance_label=instance_label,
        health_path=health_path,
        traefik_host=traefik_host,
        traefik_path=traefik_path,
        traefik_service_name=traefik_service_name,
        nats_queue=nats_queue,
        nats_url=nats_url,
        traefik_labels=traefik_labels,
        infisical_env=infisical_env,
        auth_env=auth_env,
        network_traefik_public=PlatformDockerConstants.NETWORK_TRAEFIK_PUBLIC,
        network_backend=PlatformDockerConstants.NETWORK_BACKEND,
        network_database=PlatformDockerConstants.NETWORK_DATABASE,
        network_infisical=PlatformDockerConstants.NETWORK_INFISICAL,
    )


def generate_backend_compose_entry(service_path, service_name, res, manifest=None):
    """
    Generate backend docker-compose entries with TRUE multi-replica support.
    """
    replicas = manifest.get('replicas', 1) if manifest else 1
    
    if replicas <= 1:
        # Single instance - simple case
        return _generate_single_backend_entry(service_path, service_name, res, manifest, instance_id=None)
    
    # Multi-replica: generate separate service entries
    entries = []
    
    # Primary instance (gets the port mapping)
    entries.append(_generate_single_backend_entry(service_path, service_name, res, manifest, instance_id=None))
    
    # Additional replicas (numbered, expose only)
    for i in range(1, replicas):
        entries.append(_generate_single_backend_entry(service_path, service_name, res, manifest, instance_id=i))
    
    return ''.join(entries)


def generate_app_compose_from_entries(service_path, service_entries, write_file_if_changed_fn=None):
    """Generate docker-compose.app.autogenerated.yml from service entries."""
    header = """###############################################################################
# 🛑 CRITICAL: SYSTEM-GENERATED FILE - DO NOT MODIFY DIRECTLY
#
# ANY MANUAL CHANGES MADE TO THIS FILE WILL BE WIPED ON THE NEXT 'tilt up'.
# Generation Source: .tilt/topologies/platform/docker/index.star
###############################################################################

x-nix-any-m1-arm64-memory-limit: &nix-any-m1-arm64-memory-limit
  deploy:
    resources:
      limits:
        memory: 192M
      reservations:
        memory: 64M

x-frontend-memory-limit: &frontend-memory-limit
  deploy:
    resources:
      limits:
        memory: 64M
        cpus: '0.15'
      reservations:
        memory: 32M

services:
"""
    footer = """
networks:
  {network_traefik_public}:
    external: true
  {network_backend}:
    external: true
  {network_database}:
    external: true
  {network_infisical}:
    external: true
""".format(
        network_traefik_public=PlatformDockerConstants.NETWORK_TRAEFIK_PUBLIC,
        network_backend=PlatformDockerConstants.NETWORK_BACKEND,
        network_database=PlatformDockerConstants.NETWORK_DATABASE,
        network_infisical=PlatformDockerConstants.NETWORK_INFISICAL,
    )
    
    content = header + "\n".join(service_entries) + footer
    
    if write_file_if_changed_fn:
        write_file_if_changed_fn(service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/docker-compose.app.autogenerated.yml', content)
    
    return content


def generate_migrator_compose(service_path, service_name, dockerfile_path=None, write_file_if_changed_fn=None):
    """Generate docker-compose for database migrators."""
    migrator_name = service_name + '-db-migrator'
    image_name = with_runtime_image_tag(service_name + '-db-migrator')
    
    db_name = 'TDK_' + service_name
    default_db_url = PlatformDockerConstants.get_database_url_for_env(db_name)

    dockerfile_ref = dockerfile_path if dockerfile_path else service_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/Dockerfile.migrator.autogenerated"
    infisical_env = get_infisical_environment_vars(as_array=False)
    
    content = """###############################################################################
# 🛑 CRITICAL: SYSTEM-GENERATED FILE - DO NOT MODIFY DIRECTLY
# Generation Source: .tilt/topologies/platform/docker/index.star
###############################################################################
# 🔐 Infisical Zero-Code Integration Enabled
# 🗃️ Database Virtualization: Connects to shared PostgreSQL instance
services:
  {migrator_name}:
    image: {image_name}
    build:
      context: ../../../../.
      dockerfile: {dockerfile_ref}
      target: migrator
    environment:
{infisical_env}
      SERVICE_NAME: {service_name}
      TILT_DATABASE_URL: "{default_db_url}"
      DATABASE_URL: ${{DATABASE_URL:-{default_db_url}}}
    networks:
      - {network_database}
      - {network_backend}
      - {network_infisical}
    restart: "no"

networks:
  {network_database}:
    external: true
  {network_backend}:
    external: true
  {network_infisical}:
    external: true
""".format(
        migrator_name=migrator_name, 
        image_name=image_name, 
        service_path=service_path,
        dockerfile_ref=dockerfile_ref,
        service_name=service_name,
        db_name=db_name,
        default_db_url=default_db_url,
        infisical_env=infisical_env,
        network_database=PlatformDockerConstants.NETWORK_DATABASE,
        network_backend=PlatformDockerConstants.NETWORK_BACKEND,
        network_infisical=PlatformDockerConstants.NETWORK_INFISICAL,
    )

    if write_file_if_changed_fn:
        write_file_if_changed_fn(service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/docker-compose.migrator.autogenerated.yml', content)

    return content
