# =============================================================================
# 🐳 TILT SDK - COMPOSE HELPERS
# =============================================================================

load("../../../../spec.master", "OUTPUT")

def with_runtime_image_tag(image_name):
    """Apply stable local image tag (:dev)."""
    tag = 'dev'

    last_segment = image_name.split('/')[-1]
    if ':' in last_segment:
        return image_name[:image_name.rfind(':')] + ':' + tag

    return image_name + ':' + tag

def compose_build_config(service_path, res_name, dockerfile=OUTPUT.AUTOGENERATED_FOLDER + '/Dockerfile.app.autogenerated', target=None):
    """Generate build config for docker-compose."""
    # Check if dockerfile is already a full path (contains service_path)
    if dockerfile.startswith(service_path + '/'):
        # dockerfile is already a full path, use it directly
        full_dockerfile_path = dockerfile
    elif res_name:
        # Nested structure: construct path as service_path/res_name/dockerfile
        full_dockerfile_path = "{service_path}/{res_name}/{dockerfile}".format(
            service_path=service_path,
            res_name=res_name,
            dockerfile=dockerfile
        )
    else:
        # Flat structure: construct path as service_path/dockerfile
        full_dockerfile_path = "{service_path}/{dockerfile}".format(
            service_path=service_path,
            dockerfile=dockerfile
        )
    
    base_config = """    build:
      context: ../../../../.
      dockerfile: {full_dockerfile_path}""".format(
        full_dockerfile_path=full_dockerfile_path
    )
    
    if target:
        base_config += """
      target: {target}""".format(target=target)
    
    return base_config
