# =============================================================================
# 📦 TILT SDK - NPM/BUN CONFIG PROVIDER
# =============================================================================
# Path: .tilt/providers/npmrc.star
# Purpose: Generate .npmrc and bunfig.toml for Verdaccio registry
# =============================================================================
#
# Generates configuration files for:
# - .npmrc / .npmrc.docker.autogenerated - NPM registry configuration
# - bunfig.toml / bunfig.docker.autogenerated.toml - Bun package manager configuration
#
# These files ensure services can install @beauty-crm/* packages from
# the local Verdaccio registry during development.
# =============================================================================

load("../../../topologies/tilt/common/utils.star", "Utils")
load("../../../topologies/tilt/manifest/constants.star", "PACKAGE_CONFIG_FILENAMES")

# =============================================================================
# 📝 NPMRC GENERATORS
# =============================================================================

def generate_npmrc(service_path, registry_url, is_docker, write_file_if_changed):
    """
    Generate .npmrc for NPM registry configuration.
    
    Args:
        service_path: Path to service directory
        registry_url: Verdaccio registry URL
        is_docker: If True, generates .npmrc.docker.autogenerated, else .npmrc
        write_file_if_changed: File writer function
    """
    registry_host = registry_url.replace("http://", "").replace("https://", "").rstrip("/")
    
    target_dir = service_path + "/autogenerated"
    generated_filename = PACKAGE_CONFIG_FILENAMES['npmrc_docker_autogenerated'] if is_docker else PACKAGE_CONFIG_FILENAMES['npmrc']
    header = Utils.get_template_header("npmrc", target_dir + "/" + generated_filename)
    content = """{header}
registry=https://registry.npmjs.org/
@beauty-crm:registry={registry_url}/
//{registry_host}/:username=admin
//{registry_host}/:_password=YWRtaW4=
//{registry_host}/:email=admin@example.com
//{registry_host}/:always-auth=true""".format(header=header, registry_url=registry_url, registry_host=registry_host)
    
    filename = generated_filename
    write_file_if_changed(target_dir + '/' + filename, content)


# =============================================================================
# 📝 BUNFIG GENERATORS
# =============================================================================

def generate_bunfig(service_path, registry_url, is_docker, write_file_if_changed):
    """
    Generate bunfig.toml for Bun package manager configuration.
    
    Args:
        service_path: Path to service directory
        registry_url: Verdaccio registry URL
        is_docker: If True, generates bunfig.docker.autogenerated.toml, else bunfig.toml
        write_file_if_changed: File writer function
    """
    target_dir = service_path + "/autogenerated"
    generated_filename = PACKAGE_CONFIG_FILENAMES['bunfig_docker_autogenerated'] if is_docker else PACKAGE_CONFIG_FILENAMES['bunfig']
    header = Utils.get_template_header("bunfig", target_dir + "/" + generated_filename)
    content = """{header}
[install]
linker = "isolated"
linkWorkspacePackages = false
registry = "https://registry.npmjs.org"

[install.scopes]
"@beauty-crm" = {{ url = "{registry_url}/" }}

""".format(header=header, registry_url=registry_url)

    filename = generated_filename
    write_file_if_changed(target_dir + '/' + filename, content)


# =============================================================================
# 🎯 PUBLIC API - Struct-based Exports
# =============================================================================

PackageConfig = struct(
    npmrc = generate_npmrc,
    bunfig = generate_bunfig,
)
