"""
L4 Runtime Layers - Final Application Runtime Stages

Handles the final runtime stages for deployed applications:
- l4_backend_runtime: Backend service runtime with Bun
- l4_frontend_runtime: Frontend runtime with Nginx or Bun static
- l4_migrator_runtime: Database migration runner with Infisical integration
"""

load('./l1_base_layers.star', 'BUN_BASE')
load('./l2_dependency_layers.star', 'normalize_res_path')
load('../../../tilt/discovery/config.star', 'GLOBAL_CONFIG')
load('../../../tilt/common/utils_debug.star', 'DEBUG_MODE')
load('../../../tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS')
load('./prisma/prisma_runtime.star',
    'prisma_runtime_copy',
    'prisma_bun_symlink_fix',
    'prisma_config_copy',
    'L4_generate_migrator_runtime',
)
load("../../../../spec.master", "OUTPUT")
load('./bun_helpers.star', 'bun_hoisted_packages_symlink_fix')
load("../../../../../.tilt/TILT_SERVICE_DEFAULTS.star", "BASE_PORT_FRONTEND", "BASE_PORT_BACKEND", "get_docker_healthcheck_config")

_docker_cfg = GLOBAL_CONFIG['docker']
GOLDEN_L4_BACKEND_IMAGE = _docker_cfg.get('golden_l4_backend_image', 'TDK Landscape-l4-backend:latest')
GOLDEN_L4_FRONTEND_IMAGE = _docker_cfg.get('golden_l4_frontend_image', 'TDK Landscape-l4-frontend:latest')

# Load Docker healthcheck configuration
_docker_health = get_docker_healthcheck_config()


def L4_generate_backend_runtime(res_path, port = BASE_PORT_BACKEND, cmd = 'bun run start', use_infisical = True, service_name = 'service', use_golden = True, has_prisma_config = False, manifest = None):
    """
    Generate the backend runtime layer for deployed services.
    
    Args:
        res_path: Resource path (service directory)
        port: Port to expose (default: BASE_PORT_BACKEND from master config)
        cmd: Command to run (default: 'bun run start')
        use_infisical: Enable Infisical secret management (default: True)
        service_name: Service name for logging and configuration (default: 'service')
        use_golden: Whether to use golden L4-backend image (default: True)
        has_prisma_config: Whether service has Prisma config (default: False)
        manifest: Service manifest dict for feature detection (default: None)
    
    Returns:
        Dockerfile content string for the l4_backend_runtime stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    # Force golden images regardless of CLI/Tilt flags.
    use_golden = True
    # Use golden L4-backend image if enabled (production-optimized backend runtime)
    base_image = GOLDEN_L4_BACKEND_IMAGE if use_golden else BUN_BASE
    
    parts = [
        "# ---- L4: backend_runtime ----\n",
        "FROM " + base_image + " AS l4_backend_runtime\n",
        "WORKDIR /app/" + res_path + "\n",
        "# Build argument to skip Infisical setup (for local dev / fast builds)\n",
        "ARG SKIP_INFISICAL_SETUP=0\n",
        "ENV NODE_ENV=production\n",
        "COPY --from=l3_production_purger /app/" + res_path + "/node_modules ./node_modules\n",
        # Bun isolated linker creates service symlinks that resolve through /app/node_modules/.bun.
        # Copy from production_purger to avoid dragging full dev dependency store into runtime.
        "COPY --from=l3_production_purger /app/" + res_path + "/node_modules/.bun /app/node_modules/.bun\n",
        prisma_runtime_copy(res_path),
        "COPY --from=l3_backend_build /app/" + res_path + "/dist ./dist\n",
        "COPY " + res_path_rel + "/package.json ./package.json\n",
        prisma_bun_symlink_fix(),
        bun_hoisted_packages_symlink_fix(),
    ]
    
    # Check for special tooling requirements from manifest features
    # Services requiring Hugo (or other tools) should specify in manifest features array
    manifest_features = manifest.get('features', []) if manifest else []
    if "hugo" in manifest_features:
        parts.append("USER root\n")
        parts.append("RUN apk add --no-cache hugo\n")
        parts.append("USER bun\n")

    if has_prisma_config:
        # Prisma v7 migrate deploy reads datasource.url from prisma.config.ts in CWD
        parts.append(prisma_config_copy(res_path))
    
    # Only set USER if not using golden image (already set in golden L4)
    if not use_golden:
        parts.append("USER bun\n")
    
    parts.extend([
        "EXPOSE " + str(port) + "\n",
    ])
    
    # Only add healthcheck if not using golden image (already in golden L4)
    if not use_golden:
        parts.append("HEALTHCHECK --interval={}s --timeout={}s --start-period={}s --retries={} CMD bun --version || exit 1\n".format(
            _docker_health["interval_seconds"],
            _docker_health["timeout_seconds"],
            _docker_health["start_period_seconds"],
            _docker_health["retries"],
        ))
    
    if use_infisical:
        # Copy entrypoint script only - Infisical CLI is NOT included in golden images
        # to avoid Cloudsmith CDN build hangs. Secrets are injected via env vars at runtime.
        # The entrypoint.sh gracefully handles missing CLI by falling back to env vars.
        # See: https://github.com/san4osq/tdk/blob/main/KNOWN_ISSUES.md
        parts.append("COPY --chmod=0755 shared-platform-engineering/docker-templates/infisical-entrypoint.sh /entrypoint.sh\n")
        
        parts.append(
            "ENV SERVICE_NAME=" + service_name + "\n"
            + "ENV INFISICAL_SECRET_PATH=/services/" + service_name + "\n"
            + "ENTRYPOINT [\"/entrypoint.sh\"]\n"
            + "CMD [\"bun\", \"run\", \"start\"]\n"
        )
    else:
        parts.append("CMD [\"" + cmd + "\"]\n")

    # Provide build targets that match external tooling (e.g. --target production/ development)
    parts.append("\nFROM l4_backend_runtime AS production\nFROM l4_backend_runtime AS development\n")

    return "".join(parts)


def L4_generate_frontend_runtime(res_path, target_path = '/usr/share/nginx/html', use_nginx = True, use_golden = True):
    """
    Generate the frontend runtime layer for static site serving.
    
    Args:
        res_path: Resource path (service directory)
        target_path: Target path for static files (default: Nginx html directory)
        use_nginx: Use Nginx for serving (default: True, uses Bun static if False)
        use_golden: Whether to use golden L4-frontend image (default: True)
    
    Returns:
        Dockerfile content string for the l4_frontend_runtime stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    # Force golden images regardless of CLI/Tilt flags.
    use_golden = True
    if use_nginx:
        # Use golden L4-frontend image if enabled (Nginx pre-configured)
        base_image = GOLDEN_L4_FRONTEND_IMAGE if use_golden else "nginx:alpine"
        
        # If using golden image, skip curl installation (already there)
        healthcheck_setup = "" if use_golden else "RUN apk add --no-cache curl\n"
        
        return (
            "# ---- L4: frontend_runtime (nginx) ----\n"
            + "FROM " + base_image + " AS l4_frontend_runtime\n"
            + healthcheck_setup
            + "COPY --from=l3_frontend_build /app/" + res_path + "/dist " + target_path + "\n"
            + "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/nginx.autogenerated.conf /etc/nginx/conf.d/default.conf\n"
            + "EXPOSE 80\n"
            + ("" if use_golden else "HEALTHCHECK --interval={}s --timeout={}s --start-period={}s --retries={} CMD curl -f http://localhost/ || exit 1\n".format(
                _docker_health["interval_seconds"],
                _docker_health["timeout_seconds"],
                _docker_health["frontend_start_period_seconds"],
                _docker_health["retries"],
            ))
            + "CMD [\"nginx\", \"-g\", \"daemon off;\"]\n"
            + "FROM l4_frontend_runtime AS production\n"
            + "FROM l4_frontend_runtime AS development\n"
        )
    # Use golden L4-frontend image even for Bun static serving (or BUN_BASE as fallback)
    # NOTE: When use_nginx=False, we MUST use BUN_BASE because the golden L4 frontend
    # image is nginx-based and doesn't have Bun installed
    base_image = GOLDEN_L4_FRONTEND_IMAGE if (use_golden and use_nginx) else BUN_BASE
    
    return (
        "# ---- L4: frontend_runtime (bun static) ----\n"
        + "FROM " + base_image + " AS l4_frontend_runtime\n"
        + "WORKDIR /app/" + res_path + "\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/dist ./dist\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/node_modules ./node_modules\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + " ./autogenerated\n"
        + "COPY " + res_path_rel + "/package.json ./package.json\n"
        + "EXPOSE " + str(BASE_PORT_FRONTEND) + "\n"
        + 'CMD ["bun", "run", "start"]\n'
        + "FROM l4_frontend_runtime AS production\n"
        + "FROM l4_frontend_runtime AS development\n"
    )


# L4_generate_migrator_runtime is now loaded from prisma/prisma_runtime.star
