load("../../../../topologies/tilt/common/utils.star", "Utils")
load("../../../../topologies/tilt/manifest/constants.star", "GENERATED_CONFIG_FILENAMES")
load("../../../../spec.master", "OUTPUT")

# =============================================================================
# Prisma Config Generator
# =============================================================================

def generate_prisma_config(service_path, service_name, db_name, write_file_if_changed):
    """
    Generate prisma.config.autogenerated.ts for Prisma v7 CLI configuration.
    """
    service_display_name = service_name

    header = Utils.get_template_header(
        GENERATED_CONFIG_FILENAMES['prisma'],
        'TypeScript.prisma()',
        service_display_name,
        'Prisma Configuration'
    )
    content = """/**
 * AUTOGENERATED Prisma CLI Configuration - %s Service
 *
 * This config is used by Prisma CLI commands (generate, migrate, db push).
 */
export default {
  schema: 'prisma/schema.prisma',
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
""" % (service_name)
    
    if write_file_if_changed:
        write_file_if_changed(service_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['prisma'], content)
